---
- hosts: all
  become: yes
  tasks:
      - name: install java for Debian
        apt:
          name: "{{openjdkforubuntu}}"
          state: absent
        when: ansible_os_family=="Debian"

      - name: install java for redat
        yum:
          name: "{{openjdkforredhat}}"
          state: absent
        when: ansible_os_family=="RedHat"
