---
- hosts: mywebserver
  become: yes
  tasks:
    - name: i want to store linux cmd in ansible
      command: hostname -f
      register: myRes
      
    - name: display result 
      debug: 
        msg: "{{myRes}}"

