---
- hosts: 172.31.18.136
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        state: present

    - name: chnage application at run time
      template: 
        src: myindex.j2
        dest: /var/www/html/index.html
