---
- hosts: mywebserver
  become: yes
  vars:
    myvar1 : tree
    myvar2 : git
    myvar3 : wget 
  tasks:
        - name: install packages
          debug:
            msg: "{{myvar2}}"
        
        - name: install java for Debian
          apt:
            name: "{{item}}"
            state: present
          when: ansible_os_family=="Debian"
          loop:
          - "{{myvar1}}"
          - "{{myvar2}}"
          - "{{myvar3}}"